### PR TITLE
Update application.properties

### PR DESCRIPTION
**Pull request by nsundara**
Hi Pablo, 

Can you check the property name changes for UCP? I thought, this was fixed but, it was still using ucp and not oracleucp.

### CODE REVIEW

**Review by psilberk — CHANGES_REQUESTED** [review]
Hi Nirmala, in order for this to work with the newer values (...oracleucp...) you have to use a SpringBoot version > 2.4 (as far as I remember). Looking at the pom file, this is 2.2.6. I'd recommend you to update SpringBoot version to 2.5 or above and test.

**Comment by nsundara** [comment]
> Hi Nirmala, in order for this to work with the newer values (...oracleucp...) you have to use a SpringBoot version > 2.4 (as far as I remember). Looking at the pom file, this is 2.2.6. I'd recommend you to update SpringBoot version to 2.5 or above and test.

**Comment by nsundara** [comment]
I updated the POM file to 2.7.0 and verified it too. Can you approve?

**Review by Kuassim — APPROVED** [review]

**Comment by nsundara** [comment]
The changes are merged as part of pull request #207

**Pull request closed without merging**
